In [1]:
import pandas as pd
from PIL.ImageChops import offset

from settings import INTERIM

In [2]:
team_splits = pd.read_pickle(INTERIM / 'team_splits_date_index.pkl')
scoring = pd.read_pickle(INTERIM / 'scoring_multi_index.pkl')

In [3]:
team_splits.head(2)

                     name    W    L    T  OL
month
1980-09-01  Boston Bruins  NaN  NaN  NaN NaN
1980-10-01  Boston Bruins  2.0  7.0  1.0 NaN

In [4]:
team_splits.loc[team_splits['name'] == 'Anaheim Ducks']

                     name     W    L   T   OL
month
2006-09-01  Anaheim Ducks   NaN  NaN NaN  NaN
2006-10-01  Anaheim Ducks   9.0  0.0 NaN  3.0
2006-11-01  Anaheim Ducks  10.0  2.0 NaN  3.0
2006-12-01  Anaheim Ducks   9.0  5.0 NaN  0.0
2006-01-01  Anaheim Ducks   4.0  5.0 NaN  2.0
2006-02-01  Anaheim Ducks   5.0  5.0 NaN  2.0
2006-03-01  Anaheim Ducks  10.0  3.0 NaN  2.0
2006-04-01  Anaheim Ducks   1.0  0.0 NaN  2.0
2007-09-01  Anaheim Ducks   1.0  1.0 NaN  0.0
2007-10-01  Anaheim Ducks   3.0  6.0 NaN  2.0
2007-11-01  Anaheim Ducks   8.0  4.0 NaN  2.0
2007-12-01  Anaheim Ducks   7.0  6.0 NaN  1.0
2007-01-01  Anaheim Ducks   8.0  4.0 NaN  1.0
2007-02-01  Anaheim Ducks  10.0  2.0 NaN  1.0
2007-03-01  Anaheim Ducks   8.0  4.0 NaN  1.0
2007-04-01  Anaheim Ducks   2.0  0.0 NaN  0.0
2008-09-01  Anaheim Ducks   NaN  NaN NaN  NaN
2008-10-01  Anaheim Ducks   6.0  5.0 NaN  1.0
2008-11-01  Anaheim Ducks   8.0  3.0 NaN  2.0
2008-12-01  Anaheim Ducks   5.0  7.0 NaN  1.0
2008-01-01  Anaheim Ducks   6.0  7.0 NaN  1.0
2008-02-01  Anaheim Ducks   6.0  6.0 NaN  0.0
2008-03-01  Anaheim Ducks   8.0  4.0 NaN  1.0
2008-04-01  Anaheim Ducks   3.0  1.0 NaN  1.0
2009-09-01  Anaheim Ducks   NaN  NaN NaN  NaN
2009-10-01  Anaheim Ducks   4.0  6.0 NaN  2.0
2009-11-01  Anaheim Ducks   6.0  5.0 NaN  2.0
2009-12-01  Anaheim Ducks   6.0  6.0 NaN  3.0
2009-01-01  Anaheim Ducks   9.0  6.0 NaN  0.0
2009-02-01  Anaheim Ducks   5.0  2.0 NaN  0.0
2009-03-01  Anaheim Ducks   7.0  6.0 NaN  1.0
2009-04-01  Anaheim Ducks   2.0  1.0 NaN  3.0
2010-09-01  Anaheim Ducks   NaN  NaN NaN  NaN
2010-10-01  Anaheim Ducks   4.0  7.0 NaN  1.0
2010-11-01  Anaheim Ducks   8.0  4.0 NaN  2.0
2010-12-01  Anaheim Ducks   8.0  6.0 NaN  1.0
2010-01-01  Anaheim Ducks   8.0  3.0 NaN  0.0
2010-02-01  Anaheim Ducks   5.0  5.0 NaN  1.0
2010-03-01  Anaheim Ducks  11.0  3.0 NaN  0.0
2010-04-01  Anaheim Ducks   3.0  2.0 NaN  0.0
2011-09-01  Anaheim Ducks   NaN  NaN NaN  NaN
2011-10-01  Anaheim Ducks   5.0  5.0 NaN  1.0
2011-11-01  Anaheim Ducks   2.0  8.0 NaN  3.0
2011-12-01  Anaheim Ducks   3.0  8.0 NaN  2.0
2011-01-01  Anaheim Ducks   9.0  2.0 NaN  1.0
2011-02-01  Anaheim Ducks   8.0  4.0 NaN  3.0
2011-03-01  Anaheim Ducks   6.0  7.0 NaN  1.0
2011-04-01  Anaheim Ducks   1.0  2.0 NaN  1.0

In [5]:
team_splits.query("name == 'Anaheim Ducks'")

                     name     W    L   T   OL
month
2006-09-01  Anaheim Ducks   NaN  NaN NaN  NaN
2006-10-01  Anaheim Ducks   9.0  0.0 NaN  3.0
2006-11-01  Anaheim Ducks  10.0  2.0 NaN  3.0
2006-12-01  Anaheim Ducks   9.0  5.0 NaN  0.0
2006-01-01  Anaheim Ducks   4.0  5.0 NaN  2.0
2006-02-01  Anaheim Ducks   5.0  5.0 NaN  2.0
2006-03-01  Anaheim Ducks  10.0  3.0 NaN  2.0
2006-04-01  Anaheim Ducks   1.0  0.0 NaN  2.0
2007-09-01  Anaheim Ducks   1.0  1.0 NaN  0.0
2007-10-01  Anaheim Ducks   3.0  6.0 NaN  2.0
2007-11-01  Anaheim Ducks   8.0  4.0 NaN  2.0
2007-12-01  Anaheim Ducks   7.0  6.0 NaN  1.0
2007-01-01  Anaheim Ducks   8.0  4.0 NaN  1.0
2007-02-01  Anaheim Ducks  10.0  2.0 NaN  1.0
2007-03-01  Anaheim Ducks   8.0  4.0 NaN  1.0
2007-04-01  Anaheim Ducks   2.0  0.0 NaN  0.0
2008-09-01  Anaheim Ducks   NaN  NaN NaN  NaN
2008-10-01  Anaheim Ducks   6.0  5.0 NaN  1.0
2008-11-01  Anaheim Ducks   8.0  3.0 NaN  2.0
2008-12-01  Anaheim Ducks   5.0  7.0 NaN  1.0
2008-01-01  Anaheim Ducks   6.0  7.0 NaN  1.0
2008-02-01  Anaheim Ducks   6.0  6.0 NaN  0.0
2008-03-01  Anaheim Ducks   8.0  4.0 NaN  1.0
2008-04-01  Anaheim Ducks   3.0  1.0 NaN  1.0
2009-09-01  Anaheim Ducks   NaN  NaN NaN  NaN
2009-10-01  Anaheim Ducks   4.0  6.0 NaN  2.0
2009-11-01  Anaheim Ducks   6.0  5.0 NaN  2.0
2009-12-01  Anaheim Ducks   6.0  6.0 NaN  3.0
2009-01-01  Anaheim Ducks   9.0  6.0 NaN  0.0
2009-02-01  Anaheim Ducks   5.0  2.0 NaN  0.0
2009-03-01  Anaheim Ducks   7.0  6.0 NaN  1.0
2009-04-01  Anaheim Ducks   2.0  1.0 NaN  3.0
2010-09-01  Anaheim Ducks   NaN  NaN NaN  NaN
2010-10-01  Anaheim Ducks   4.0  7.0 NaN  1.0
2010-11-01  Anaheim Ducks   8.0  4.0 NaN  2.0
2010-12-01  Anaheim Ducks   8.0  6.0 NaN  1.0
2010-01-01  Anaheim Ducks   8.0  3.0 NaN  0.0
2010-02-01  Anaheim Ducks   5.0  5.0 NaN  1.0
2010-03-01  Anaheim Ducks  11.0  3.0 NaN  0.0
2010-04-01  Anaheim Ducks   3.0  2.0 NaN  0.0
2011-09-01  Anaheim Ducks   NaN  NaN NaN  NaN
2011-10-01  Anaheim Ducks   5.0  5.0 NaN  1.0
2011-11-01  Anaheim Ducks   2.0  8.0 NaN  3.0
2011-12-01  Anaheim Ducks   3.0  8.0 NaN  2.0
2011-01-01  Anaheim Ducks   9.0  2.0 NaN  1.0
2011-02-01  Anaheim Ducks   8.0  4.0 NaN  3.0
2011-03-01  Anaheim Ducks   6.0  7.0 NaN  1.0
2011-04-01  Anaheim Ducks   1.0  2.0 NaN  1.0

In [6]:
ducks = team_splits.loc[team_splits['name'] == 'Anaheim Ducks']

In [7]:
ducks = ducks.sort_index()

In [9]:
ducks.resample('YE')[['W', 'L', 'T', 'OL']].sum()

               W     L    T    OL
month
2006-12-31  48.0  20.0  0.0  14.0
2007-12-31  47.0  27.0  0.0   8.0
2008-12-31  42.0  33.0  0.0   7.0
2009-12-31  39.0  32.0  0.0  11.0
2010-12-31  47.0  30.0  0.0   5.0
2011-12-31  34.0  36.0  0.0  12.0

In [10]:
ducks.resample('YE-JUN')[['W', 'L', 'T', 'OL']].sum()

               W     L    T    OL
month
2006-06-30  20.0  13.0  0.0   8.0
2007-06-30  56.0  17.0  0.0   9.0
2008-06-30  42.0  35.0  0.0   8.0
2009-06-30  42.0  30.0  0.0   8.0
2010-06-30  43.0  30.0  0.0   8.0
2011-06-30  44.0  32.0  0.0  10.0
2012-06-30  10.0  21.0  0.0   6.0

In [11]:
ducks.resample('YE', offset='6MS')[['W', 'L', 'T', 'OL']].sum()

               W     L    T    OL
month
2006-12-31  48.0  20.0  0.0  14.0
2007-12-31  47.0  27.0  0.0   8.0
2008-12-31  42.0  33.0  0.0   7.0
2009-12-31  39.0  32.0  0.0  11.0
2010-12-31  47.0  30.0  0.0   5.0
2011-12-31  34.0  36.0  0.0  12.0